### ISSUE TITLE
removing numbers in numbers column

### ISSUE THREAD

**Issue by NoamMuallem** [JonasLeonhard/lvim-config#1]
Hi, thank for a great config, first time I can actually debug in nvim (with your dap set up), but I just wonted to know a few things:
1.how to remap <leader>gd and <leader>gg? I cant override them...
2.how to remove this numbers in the number column?
<img width="87" alt="Screen Shot 2022-11-01 at 23 21 01" src="https://user-images.githubusercontent.com/40291455/199284131-ac8e4e5c-3af5-47ac-9100-4011418667e4.png">

**Comment by JonasLeonhard** [comment]
Hey @NoamMuallem,

im using the ufo plugin for these folds, the creator has an issue where he builds neovim from source with slight changes: https://github.com/kevinhwang91/nvim-ufo/issues/4 . I had the same issue with folds, and found no other workaround, let me know if you find one without changing neovims source code and recompiling. 

As for remapping "gd" and "gg", do you mean the wich_keys? (<space>-gd) to open lazygit / open git diff?
To remap those you could change 
`lvim.builtin.which_key.mappings["gd"] = { "<cmd>Mason<cr>", "Open Mason" };` for example.
